language: python
python:
  #- "2.6" # does not pass: OrderedDict not available
  - "2.7"
  - "3.2"
  - "3.3"

# command to install dependencies
install: 
  - "pip install coveralls"
  - "pip install -r requirements.txt"
  - "pip install ."
  - "pip install ./testing"

# command to run tests
script: 
  - env PYTHONPATH="${PWD}:$PYTHNPATH" coverage run --source=rubik,rubik.application,rubik.application.help_functions,rubik.cubes --omit "*/visualizer/*" `which rubik_test`

after_success:
  - coveralls --rcfile=testing/.coveragerc

# notifications:
notifications:
  email:
    recipients:
      - simone.campagna11@gmail.com
    on_success: change
    on_failure: always
