language: python
python:
  #- "2.6"
  - "2.7"
  - "3.2"
  - "3.3"

# command to install dependencies
install: 
  - "pip install coveralls"
  - "pip install numpy"
  - "pip install ."

# command to run tests
script: 
  - PYTHONPATH="${PWD}:$PYTHONPATH" coverage run --source=rubik,rubik.application,rubik.application.help_functions,rubik.cubes --omit "*/visualizer/*" ./bin/rubik_test

after_success:
  - coveralls --rcfile=.coveragerc

# notifications:
notifications:
  email:
    recipients:
      - simone.campagna11@gmail.com
    on_success: change
    on_failure: always
