#!/bin/bash

TEMPROOT="$PWD/tmp_test_cubist.$$"
TEMPDIR=""
while [[ ${#@} -ne 0 ]] ; do
    option="$1"
    shift 1
    case "$option" in
        --tmpdir|-t)
            TEMPDIR="$1"
            shift 1
            ;;
        --help|-h)
            print_help
            ;;
        *)
            echo "ERR: invalid argument '${option}'" 1>&2
            exit 1
            ;;
    esac
done

if [[ "$TEMPDIR" == "" ]] ; then
    unset TEMPDIR
    while [[ -d ${TEMPDIR:=${TEMPROOT}.$RANDOM} ]] ; do
        unset TEMPDIR
    done
fi

echo "== TEMPDIR=$TEMPDIR"

mkdir -p $TEMPDIR

cd $TEMPDIR

function prex {
    typeset    _command="$1"
    typeset -i _returncode
    echo ">>> $_command ..." 1>&2
    eval "$_command" ; _returncode=$?
    echo "<<< $_command [${_returncode}]" 1>&2
    return $_returncode
}

function die {
    typeset    _message="$1"
    typeset -i _exitcode=${2:-1}
    echo "ERR: $_message [exiting ${_exitcode}]" 1>&2
    exit $_exitcode
}

function check_file_exists {
    typeset _filename="$1"
    if [[ -f "$_filename" ]] ; then
        echo ".... OK, $_filename exists"
    else
        die "file $_filename does not exists"
    fi
}

function check_file_has_size {
    typeset _filename="$1"
    typeset _filesize="$2"
    typeset _statsize=$(stat --printf %s "$_filename")
    if [[ $_filesize -eq $_statsize ]] ; then
        echo ".... OK, $_filename has size ${_filesize}"
    else
        die "file $_filename has size ${_statsize} != expected size ${_filesize}"
    fi
}

function check_file_exists_and_has_size {
    typeset _filename="$1"
    typeset _filesize="$2"
    check_file_exists "$_filename"
    check_file_has_size "$_filename" "$_filesize"
}

## creating
typeset -i X=8
typeset -i Y=10
typeset -i bytes_float32=4
prex "cubist -o a_{shape}.{format} -e 'cnp.random_cube(($X, $Y))'"
check_file_exists_and_has_size a_${X}x${Y}.raw $(( $X * $Y * ${bytes_float32} ))

prex "cubist -o b_{shape}.{format} -e 'cnp.random_cube((${X}, ${Y}))'"
check_file_exists_and_has_size a_${X}x${Y}.raw $(( $X * $Y * ${bytes_float32} ))

prex "cubist -o c_{shape}.{format} -e 'cnp.random_cube((${X}, ${Y}))'"
check_file_exists_and_has_size a_${X}x${Y}.raw $(( $X * $Y * ${bytes_float32} ))

prex "cubist -o l_{shape}.{format} -e 'cnp.linear_cube((${X}, ${Y}))'"
check_file_exists_and_has_size a_${X}x${Y}.raw $(( $X * $Y * ${bytes_float32} ))

## checks
prex "cubist -i a_{shape}.{format} -i b_{shape}.{format} -s 8x10 -o u_{shape}.{format} -e 'i0 - i1'"
check_file_exists_and_has_size u_${X}x${Y}.raw $(( $X * $Y * ${bytes_float32} ))

