#!/bin/bash

TEMPROOT="$PWD/tmp_test_cubist.$$"
TEMPDIR=""
while [[ ${#@} -ne 0 ]] ; do
    option="$1"
    shift 1
    case "$option" in
        --tmpdir|-t)
            TEMPDIR="$1"
            shift 1
            ;;
        --help|-h)
            print_help
            ;;
        *)
            echo "ERR: invalid argument '${option}'" 1>&2
            exit 1
            ;;
    esac
done

if [[ "$TEMPDIR" == "" ]] ; then
    unset TEMPDIR
    while [[ -d ${TEMPDIR:=${TEMPROOT}.$RANDOM} ]] ; do
        unset TEMPDIR
    done
fi

function prex {
    typeset    _command="$1"
    typeset -i _returncode
    echo ">>> $_command ..." 1>&2
    eval "$_command" ; _returncode=$?
    echo "<<< $_command [${_returncode}]" 1>&2
    return $_returncode
}

function die {
    typeset    _message="$1"
    typeset -i _exitcode=${2:-1}
    echo "ERR: $_message [exiting ${_exitcode}]" 1>&2
    exit $_exitcode
}

function check_file_exists {
    typeset _filename="$1"
    if [[ -f "$_filename" ]] ; then
        echo ".... OK, $_filename exists"
    else
        die "file $_filename does not exists"
    fi
}

function check_file_has_size {
    typeset _filename="$1"
    typeset _filesize="$2"
    typeset _statsize=$(stat --printf %s "$_filename")
    if [[ $_filesize -eq $_statsize ]] ; then
        echo ".... OK, $_filename has size ${_filesize}"
    else
        die "file $_filename has size ${_statsize} != expected size ${_filesize}"
    fi
}

function check_file_exists_and_has_size {
    typeset _filename="$1"
    typeset _filesize="$2"
    check_file_exists "$_filename"
    check_file_has_size "$_filename" "$_filesize"
}

function check_files_are_equal {
    typeset _filename_a="$1"
    typeset _filename_b="$2"
    if prex "cmp $_filename_a $_filename_b" ; then # 1>/dev/null 2>&1 ; then
        echo ".... OK, $_filename_a and $_filename_b are equal"
    else
        die "file $_filename_a is NOT equal to $_filename_b: $(cmp $_filename_a $_filename_b)"
    fi
}

## setup
echo "== TEMPDIR=$TEMPDIR"

mkdir -p $TEMPDIR

prex "rm -rf ${TEMPDIR:-undefined}/*"
cd $TEMPDIR

## creating
typeset -i X=8
typeset -i Y=10
typeset -i H=30
typeset -i bytes_float16=2
typeset -i bytes_float32=4
typeset -i bytes_float64=8
prex "cubist -o a_{shape}.{format} -e 'cnp.linear_cube(($X, $Y))'"
check_file_exists_and_has_size a_${X}x${Y}.raw $(( $X * $Y * ${bytes_float32} ))

prex "cubist -o b_{shape}.{format} -e 'cnp.linear_cube((${X}, ${Y}))'"
check_file_exists_and_has_size a_${X}x${Y}.raw $(( $X * $Y * ${bytes_float32} ))

prex "cubist -o c_{shape}.{format} -e 'cnp.linear_cube((${X}, ${Y}))'"
check_file_exists_and_has_size a_${X}x${Y}.raw $(( $X * $Y * ${bytes_float32} ))

prex "cubist -o l_{shape}.{format} -e 'cnp.linear_cube((${X}, ${Y}))'"
check_file_exists_and_has_size a_${X}x${Y}.raw $(( $X * $Y * ${bytes_float32} ))

prex "cubist -o a_{shape}.{format} -e 'cnp.linear_cube((${X}, ${H}, ${Y}))'"
check_file_exists_and_has_size a_${X}x${H}x${Y}.raw $(( $X * $H * $Y * ${bytes_float32} ))

prex "cubist -o f_{shape}.{dtype}.{format} -t float16 -e 'cnp.linear_cube((8, 10))'"
check_file_exists_and_has_size f_${X}x${Y}.float16.raw $(( $X * $Y * ${bytes_float16} ))

prex "cubist -o g_{shape}.{dtype}.{format} -t float64 -e 'cnp.linear_cube((8, 10))'"
check_file_exists_and_has_size g_${X}x${Y}.float64.raw $(( $X * $Y * ${bytes_float64} ))

## checks
prex "cubist -i a_{shape}.{format} -i b_{shape}.{format} -s 8x10 -o u_{shape}.{format} -e 'i0 - i1'"
check_file_exists_and_has_size u_${X}x${Y}.raw $(( $X * $Y * ${bytes_float32} ))

prex "cubist -i a_{shape}.{format} -s 8x30x10 -x :x5x: -o tmp_{shape}.{format}"
check_file_exists_and_has_size tmp_${X}x${Y}.raw $(( $X * $Y * ${bytes_float32} ))

## --- different shapes ---
prex "cubist -i tmp_{shape}.{format} -i a_{shape}.{format} -s 8x10 -e 'i0 - i1' -o out0_{shape}.{format}"
check_file_exists_and_has_size out0_${X}x${Y}.raw $(( $X * $Y * ${bytes_float32} ))

prex "cubist -i a_{shape}.{format} -s 8x30x10 -i a_{shape}.{format} -s 8x10 -e 'i0[:, 5, :] - i1' -o out1_{shape}.{format}"
check_file_exists_and_has_size out1_${X}x${Y}.raw $(( $X * $Y * ${bytes_float32} ))
check_files_are_equal out0_${X}x${Y}.raw out1_${X}x${Y}.raw

## --- different dtypes ---
prex "cubist -i f_{shape}.{dtype}.{format} -It float16 -o tmp_f_{shape}.{dtype}.{format} -Ot float64 -s 8x10"
check_file_exists_and_has_size tmp_f_${X}x${Y}.float64.raw $(( $X * $Y * ${bytes_float64} ))

prex "cubist -i g_{shape}.{dtype}.{format} -i tmp_f_{shape}.{dtype}.{format} -t float64 -o out0_{shape}.{dtype}.{format} -s 8x10 -e 'i0 - i1'"
check_file_exists_and_has_size out0_${X}x${Y}.float64.raw $(( $X * $Y * ${bytes_float64} ))

prex "cubist -i g_{shape}.{dtype}.{format} -It float64 -i f_{shape}.{dtype}.{format} -It float16 -s 8x10 -o out1_{shape}.{dtype}.{format} -e 'i0 - i1' -Ot float64"
check_file_exists_and_has_size out1_${X}x${Y}.float64.raw $(( $X * $Y * ${bytes_float64} ))
check_files_are_equal out0_${X}x${Y}.float64.raw out1_${X}x${Y}.float64.raw

## --- user defined variables ---
prex "cubist -i a=a_{shape}.{format} -i b=b_{shape}.{format} -s 8x10 -o r0_{shape}.{format} -V f_a=10.0 -V f_b=-5.0 -e 'f_a * a + f_b * b'"
check_file_exists_and_has_size r0_${X}x${Y}.raw $(( $X * $Y * ${bytes_float32} ))

prex "cubist -i a=a_{shape}.{format} -i b=b_{shape}.{format} -s 8x10 -o r1_{shape}.{format} -V c='10.0 * a' -V d='-5.0 * b' -e 'c + d'"
check_file_exists_and_has_size r1_${X}x${Y}.raw $(( $X * $Y * ${bytes_float32} ))
check_files_are_equal r0_${X}x${Y}.raw r1_${X}x${Y}.raw

