#!/usr/bin/env python

from rubik.visualizers.impl.controller import Controller
from rubik.visualizers.impl.volume_slicer_viewer import VolumeSlicerViewer
from rubik import cubes as cb
from rubik.application.log import get_logger, set_logger

cube = cb.random_cube("20x30x40x50")
attributes = {
    'x': 7,
    'slicing_axis': 'w',
}

logger = set_logger(verbose_level=3)


controller = Controller(logger=logger, attributes=attributes, data=cube)
controller.add_viewer(viewer_class=VolumeSlicerViewer)

controller.run()
