#!/usr/bin/env python
#
# Copyright 2014 Simone Campagna
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

__author__ = "Simone Campagna"

from rubik.cubes.api import set_random_seed

from rubik.testing.rubik_test_suite import RubikTestSuite
from rubik.testing.rubik_test_runner import RubikTestRunner
from rubik.testing.tests import SUITES


if __name__ == "__main__":
    # global setup
    set_random_seed(100)
    
    # create runner
    rubik_test_runner = RubikTestRunner()

    # create suite
    rubik_test_suite = RubikTestSuite()

    # add suites
    for suite_name, suite in SUITES.iteritems():
        print "=== suite {!r}:".format(suite_name)
        rubik_test_suite.addTest(suite)

    # run tests
    rubik_test_runner.run(rubik_test_suite)

